<?php

return [
    'dsn' => env('ASE_DSN'),
    'token' => env('ASE_TOKEN'),
    'endpoint' => env('ASE_ENDPOINT', 'https://api-ase.parkwebit.nl/api/v1/ingest/envelope'),
    'enabled' => env('ASE_ENABLED', true),
    'release' => env('ASE_RELEASE'),
    'environment' => env('ASE_ENVIRONMENT', env('APP_ENV')),
    'deploy_id' => env('ASE_DEPLOY_ID'),
    'capture_warnings' => true,
    'debug' => env('ASE_DEBUG', false),
    'send_default_pii' => false,
    'sample_rate' => 1.0,
    'timeout' => 1.5,
    'max_retries' => 1,
    'gzip' => true,
    'transport' => env('ASE_TRANSPORT', 'sync'), // sync|queue|buffer
    'queue' => env('ASE_QUEUE', 'ase'),
    'offline_buffer_path' => storage_path('framework/ase/offline-buffer.jsonl'),
    'observability' => [
        'requests' => env('ASE_TRACE_REQUESTS', true),
        'outgoing_requests' => env('ASE_TRACE_OUTGOING_REQUESTS', true),
        'notifications' => env('ASE_TRACE_NOTIFICATIONS', true),
        'jobs' => env('ASE_TRACE_JOBS', true),
        'queries' => env('ASE_TRACE_QUERIES', true),
        'query_threshold_ms' => env('ASE_QUERY_THRESHOLD_MS', 100),
        'mail' => env('ASE_TRACE_MAIL', true),
        'commands' => env('ASE_TRACE_COMMANDS', true),
        'cache' => env('ASE_TRACE_CACHE', true),
        'scheduled_tasks' => env('ASE_TRACE_SCHEDULED_TASKS', true),
        'include_query_bindings' => env('ASE_INCLUDE_QUERY_BINDINGS', false),
        'ignored_paths' => ['api/v1/ingest/*'],
    ],
];
